name: ChatScape
main: com.thedreamsanctuary.chatscape.ChatScape
version: ${project.version}
author: xRezel
depend: [Vault]
commands:

   wl:
     description: Toggles Group list on and off while in private mode
     aliases: [wl]
     usage:
     
   gl:
     description: Toggles whisper list on and off while in private mode
     aliases: [gl]
     permission: dreamtools.togglewl
     usage:
         
   private:
     description: allows user to turn off all general chat -VA (Vanishes all players from sight except  those on whisper list!
     aliases: [private]
     usage:

   public:
     description: Re enables all player chat
     aliases: [public]
     usage:

 